const app=document.querySelector("#app"),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let student=JSON.parse(localStorage.getItem("geo_student")||'{"name":"","className":""}'),localResults=JSON.parse(localStorage.getItem("geo_results")||"[]"),session=null,timerHandle=null,submitting=false,musicOn=true,audioCtx=null,musicTimer=null;
document.addEventListener("click",e=>{if(e.target.dataset.r)location.hash=e.target.dataset.r});window.addEventListener("hashchange",render);
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function identity(){return `<div class="identity"><input id="sname" placeholder="Họ và tên" value="${esc(student.name)}"><input id="sclass" placeholder="Lớp, VD 12A1" value="${esc(student.className)}"><button class="primary" id="saveStudent">Lưu</button></div>`}
function bindIdentity(){let b=$("#saveStudent");if(!b)return;b.onclick=()=>{student={name:$("#sname").value.trim(),className:$("#sclass").value.trim()};localStorage.setItem("geo_student",JSON.stringify(student));alert("Đã lưu thông tin học sinh.")}}
function lessonById(id){return GEO_LESSONS.find(x=>x.id===id)}
function card(l){return `<article class="card"><span class="badge">${esc(l.short)}</span><h3>${esc(l.title)}</h3><p>Ngân hàng: ${l.bank.mcq.length} trắc nghiệm • ${l.bank.tf.length} đúng/sai • ${l.bank.short.length} trả lời ngắn.</p><div class="actions"><button class="secondary" onclick="openLesson('${l.id}','theory')">Lí thuyết</button><button class="primary" onclick="openLesson('${l.id}','practice')">Luyện tập</button></div></article>`}
function placeholderCard(x){return `<article class="card placeholder disabled"><span class="badge">${esc(x[1])}</span><h3>${esc(x[2])}</h3><p>Khung đã tạo sẵn. Chỉ cần bổ sung ngân hàng câu hỏi và infographic.</p><button class="secondary" disabled>Chưa có nội dung</button></article>`}
function home(){let h=`<section class="hero"><h1>ÔN TẬP ĐỊA LÍ 12</h1><p>Ôn theo bài • luyện 28 câu • 40 lệnh • 10 điểm</p></section>`;for(const s of GEO_SECTIONS){h+=`<section class="section"><h2>${esc(s.title)}</h2><div class="cards">`;if(s.lessonIds)h+=s.lessonIds.map(id=>card(lessonById(id))).join("");if(s.placeholders)h+=s.placeholders.map(placeholderCard).join("");if(s.mockCount)for(let i=1;i<=s.mockCount;i++)h+=`<article class="card placeholder disabled"><span class="badge">Đề ${i}</span><h3>Đề minh hoạ ${i}</h3><p>28 câu • 40 lệnh • mỗi lệnh 0,25 điểm.</p><button class="secondary" disabled>Chưa có đề</button></article>`;h+=`</div></section>`}app.innerHTML=h}
function listing(mode){app.innerHTML=`${identity()}<div class="pagehead"><h1>${mode==="theory"?"Lí thuyết / Infographic":"Luyện tập theo bài"}</h1></div>`+GEO_SECTIONS.filter(s=>s.lessonIds).map(s=>`<section class="section"><h2>${esc(s.title)}</h2><div class="cards">${s.lessonIds.map(id=>card(lessonById(id))).join("")}</div></section>`).join("");bindIdentity()}
window.openLesson=(id,mode)=>location.hash=`lesson/${id}/${mode}`;
function openLessonView(id,mode){let l=lessonById(id);if(!l)return home();if(mode==="theory"){app.innerHTML=`<div class="pagehead"><span class="badge">${l.short}</span><h1>${esc(l.title)}</h1><p>Ôn nhanh bằng sơ đồ tư duy / infographic.</p></div><div class="gallery">${(l.images||[]).map((x,i)=>`<figure><img src="${esc(x)}" alt="Infographic ${esc(l.short)} ${i+1}" loading="lazy"><figcaption>${esc(l.short)} • Infographic ${i+1}</figcaption></figure>`).join("")||"<div class='card'>Chưa có infographic.</div>"}</div>`}else{app.innerHTML=`${identity()}<div class="pagehead"><span class="badge">${l.short}</span><h1>${esc(l.title)}</h1><p>Mỗi lượt: 28 câu • 40 lệnh • 45 phút. Trắc nghiệm 40% Nhận biết – 30% Thông hiểu – 30% Vận dụng.</p></div><div class="card"><p><b>Ngân hàng:</b> ${l.bank.mcq.length} trắc nghiệm, ${l.bank.tf.length} đúng/sai, ${l.bank.short.length} trả lời ngắn.</p><button class="primary" onclick="startQuiz('${l.id}')">Bắt đầu làm bài</button></div>`;bindIdentity()}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function qkey(q){return q.id||q.q||q.intro||Math.random().toString()}
function pickUnseen(id,type,pool,count,level=""){let key=`seen_${id}_${type}_${level}`,seen=JSON.parse(localStorage.getItem(key)||"[]"),set=new Set(seen),fresh=shuffle(pool.filter(q=>!set.has(qkey(q)))),old=shuffle(pool.filter(q=>set.has(qkey(q)))),chosen=[...fresh,...old].slice(0,Math.min(count,pool.length)),keys=chosen.map(qkey),upd=[...new Set([...seen,...keys])];localStorage.setItem(key,JSON.stringify(upd.length>=pool.length?keys:upd));return chosen}
function allocation(n){let ratios=[.4,.3,.3],raw=ratios.map(x=>x*n),base=raw.map(Math.floor),left=n-base.reduce((a,b)=>a+b,0),rem=raw.map((x,i)=>({i,r:x-base[i]})).sort((a,b)=>b.r-a.r);for(let k=0;k<left;k++)base[rem[k].i]++;return {NB:base[0],TH:base[1],VD:base[2]}}
function shuffleOptions(q){let z=q.a.map((text,i)=>({text,i}));for(let i=z.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[z[i],z[j]]=[z[j],z[i]]}return {...q,a:z.map(x=>x.text),correct:z.findIndex(x=>x.i===q.correct)}}
window.startQuiz=function(id){if(!student.name||!student.className){alert("Vui lòng nhập Họ tên và Lớp trước khi làm bài.");return}let l=lessonById(id),shortCount=Math.min(6,l.bank.short.length),mcqCount=18+(6-shortCount),tfCount=Math.min(4,l.bank.tf.length),al=allocation(mcqCount),chosen=[];for(const lv of ["NB","TH","VD"]){let pool=l.bank.mcq.filter(q=>q.level===lv);chosen.push(...pickUnseen(id,"mcq",pool,al[lv],lv).map(shuffleOptions))}let used=new Set(chosen.map(qkey));if(chosen.length<mcqCount)chosen.push(...pickUnseen(id,"mcqfill",l.bank.mcq.filter(q=>!used.has(qkey(q))),mcqCount-chosen.length).map(shuffleOptions));let tf=pickUnseen(id,"tf",l.bank.tf,tfCount),sh=pickUnseen(id,"short",l.bank.short,shortCount),qs=[...chosen.map(q=>({type:"mcq",...q})),...tf.map(q=>({type:"tf",...q})),...sh.map(q=>({type:"short",...q}))];session={lesson:l,qs,i:0,answers:Array(qs.length).fill(null),endsAt:Date.now()+45*60*1000,warn10:false,warn5:false,warn1:false};startMusic();drawQ();startTimer()}
function isAnswered(q,a){if(q.type==="mcq")return Number.isInteger(a);if(q.type==="tf")return Array.isArray(a)&&q.statements.every((_,j)=>typeof a[j]==="boolean");return String(a??"").trim()!==""}
function imgHtml(q){return (q.images||[]).map(x=>`<img class="qimg" src="${esc(x)}">`).join("")}
function drawQ(){let {lesson:l,qs,i}=session,q=qs[i],answered=qs.filter((x,k)=>isAnswered(x,session.answers[k])).length,body="";if(q.type==="mcq")body=`${imgHtml(q)}<div class="answers">${q.a.map((x,j)=>`<button class="answer ${session.answers[i]===j?"selected":""}" data-j="${j}"><span class="radio"></span><span><span class="choice">${"ABCD"[j]}.</span> <span class="answertext">${esc(x)}</span></span></button>`).join("")}</div>`;if(q.type==="tf")body=`<p>${esc(q.intro)}</p>${imgHtml(q)}${q.statements.map((s,j)=>`<div class="tfrow"><div class="tfstatement"><b>${String.fromCharCode(97+j)})</b> ${esc(s.text)}</div><div class="tfopts"><label><input type="radio" name="tf${j}" value="1" ${Array.isArray(session.answers[i])&&session.answers[i][j]===true?"checked":""}> Đúng</label><label><input type="radio" name="tf${j}" value="0" ${Array.isArray(session.answers[i])&&session.answers[i][j]===false?"checked":""}> Sai</label></div></div>`).join("")}`;if(q.type==="short")body=`${imgHtml(q)}<div class="short"><input id="shortAnswer" placeholder="Nhập đáp án" value="${esc(session.answers[i]??"")}"></div>`;app.innerHTML=`<div class="quiz"><div class="quiz-topbar"><div><b>Câu ${i+1}/${qs.length}</b><div style="color:var(--muted)">Đã trả lời ${answered}/${qs.length}</div></div><div>⏱ <span id="timer" class="timer">45:00</span></div></div><div class="progress"><div style="width:${(i+1)/qs.length*100}%"></div></div><div class="pagehead"><span class="badge">${l.short}</span><h1>${esc(l.title)}</h1></div><article class="qbox"><div class="qmeta"><span>${q.type==="mcq"?"Trắc nghiệm":q.type==="tf"?"Đúng/Sai":"Trả lời ngắn"}</span><span>Mỗi lệnh đúng 0,25 điểm</span></div><h2>${q.type==="mcq"?esc(q.q):q.type==="tf"?"Chọn Đúng hoặc Sai cho từng ý":esc(q.q)}</h2>${body}<div class="quiz-actions"><button class="secondary" id="prev" ${i===0?"disabled":""}>← Câu trước</button>${i<qs.length-1?'<button class="primary" id="next">Câu tiếp →</button>':'<button class="primary" id="submit">Nộp bài</button>'}</div></article></div>`;if(q.type==="mcq")$$(".answer").forEach(b=>b.onclick=()=>{session.answers[i]=+b.dataset.j;drawQ()});if(q.type==="tf")q.statements.forEach((_,j)=>$$(`input[name="tf${j}"]`).forEach(x=>x.onchange=()=>{let a=Array.isArray(session.answers[i])?[...session.answers[i]]:[];a[j]=x.value==="1";session.answers[i]=a}));if(q.type==="short")$("#shortAnswer").oninput=e=>session.answers[i]=e.target.value;$("#prev").onclick=()=>{saveShort();session.i--;drawQ()};if($("#next"))$("#next").onclick=()=>{saveShort();if(!isAnswered(q,session.answers[i])){alert(q.type==="tf"?"Em cần trả lời đủ cả 4 ý trước khi sang câu tiếp theo.":"Em cần trả lời câu này trước khi sang câu tiếp theo.");return}session.i++;drawQ()};if($("#submit"))$("#submit").onclick=()=>{saveShort();if(!session.qs.every((x,k)=>isAnswered(x,session.answers[k]))){alert("Em còn câu chưa trả lời.");return}if(confirm("Em đã trả lời đủ. Nộp bài ngay?"))finishQuiz(false)};updateTimer()}
function saveShort(){if(session&&session.qs[session.i]?.type==="short"&&$("#shortAnswer"))session.answers[session.i]=$("#shortAnswer").value}
function startTimer(){clearInterval(timerHandle);timerHandle=setInterval(updateTimer,1000)}
function updateTimer(){if(!session)return;let s=Math.max(0,Math.ceil((session.endsAt-Date.now())/1000)),el=$("#timer");if(el){el.textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;el.className="timer"+(s<=60?" danger":s<=300?" warn":"")}if(s<=600&&!session.warn10){session.warn10=true;alert("Còn 10 phút.")}if(s<=300&&!session.warn5){session.warn5=true;alert("Còn 5 phút.")}if(s<=60&&!session.warn1){session.warn1=true;alert("Còn 1 phút.")}if(s<=0&&!submitting){clearInterval(timerHandle);finishQuiz(true)}}
function normShort(x){return String(x??"").trim().toLowerCase().replace(/\s+/g," ").replace(",",".").replace(/[°%a-zA-Z²³]+$/g,"").trim()}function shortCorrect(got,ans){let a=normShort(got),b=normShort(ans),na=Number(a),nb=Number(b);if(Number.isFinite(na)&&Number.isFinite(nb))return Math.abs(na-nb)<.051;return a===b}
function evaluate(){let correct=0,commands=0,details=[];session.qs.forEach((q,i)=>{let a=session.answers[i],ok=false;if(q.type==="mcq"){commands++;ok=a===q.correct;if(ok)correct++;details.push({q,a,ok,cmd:1,good:ok?1:0})}if(q.type==="tf"){let good=0;q.statements.forEach((s,j)=>{commands++;if(a?.[j]===s.correct){correct++;good++}});details.push({q,a,ok:good===4,cmd:4,good})}if(q.type==="short"){commands++;ok=shortCorrect(a,q.answer);if(ok)correct++;details.push({q,a,ok,cmd:1,good:ok?1:0})}});return {correct,commands,score:Math.round(correct*.25*100)/100,details}}
function personalized(ev){let mcq=ev.details.filter(d=>d.q.type==="mcq"),by={NB:[0,0],TH:[0,0],VD:[0,0]};mcq.forEach(d=>{by[d.q.level][1]++;if(d.ok)by[d.q.level][0]++});let pct=x=>x[1]?Math.round(x[0]/x[1]*100):0,strong=[],need=[];[["Nhận biết",by.NB],["Thông hiểu",by.TH],["Vận dụng",by.VD]].forEach(([n,x])=>(pct(x)>=75?strong:need).push(`${n} (${pct(x)}%)`));let tf=ev.details.filter(d=>d.q.type==="tf"),sh=ev.details.filter(d=>d.q.type==="short"),out=`<div class="personal"><h3>🎯 Đánh giá cá nhân hoá</h3><p><b>Em làm tốt:</b> ${strong.length?strong.join(", "):"chưa có mức độ nổi trội"}.</p><p><b>Cần củng cố:</b> ${need.length?need.join(", "):"các mức độ đang khá đồng đều"}.</p>`;if(tf.length){let g=tf.reduce((s,d)=>s+d.good,0),n=tf.length*4;out+=`<p><b>Kĩ năng Đúng/Sai:</b> đúng ${g}/${n} ý (${Math.round(g/n*100)}%).</p>`}if(sh.length){let g=sh.filter(d=>d.ok).length;out+=`<p><b>Kĩ năng tính toán/trả lời ngắn:</b> đúng ${g}/${sh.length} câu. ${g<sh.length?"Nên xem lại cách tính ngay dưới các câu sai.":"Thực hiện tốt."}</p>`}return out+`</div>`}
async function saveRemote(row){if(!RESULT_API_URL)return;let payload=JSON.stringify(row);try{if(navigator.sendBeacon&&navigator.sendBeacon(RESULT_API_URL,new Blob([payload],{type:"text/plain;charset=utf-8"})))return}catch(e){}for(let k=0;k<3;k++){try{let ctl=new AbortController();setTimeout(()=>ctl.abort(),5000);await fetch(RESULT_API_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:payload,signal:ctl.signal});return}catch(e){await new Promise(r=>setTimeout(r,700*(k+1)))}}}
async function finishQuiz(auto=false){if(submitting)return;submitting=true;saveShort();clearInterval(timerHandle);stopMusic();let ev=evaluate(),row={timestamp:new Date().toISOString(),studentName:student.name,className:student.className,lessonId:session.lesson.id,lessonTitle:session.lesson.title,score:ev.score,correct:ev.correct,commands:ev.commands};localResults.push(row);localStorage.setItem("geo_results",JSON.stringify(localResults));showResult(ev,auto);saveRemote(row).finally(()=>submitting=false)}
function showResult(ev,auto){app.innerHTML=`<div class="result"><h1>Hoàn thành ${esc(session.lesson.short)}</h1>${auto?'<p>⏱ Hết 45 phút – bài đã tự động nộp.</p>':""}<div class="score">${ev.score}/10</div><p>Đúng ${ev.correct}/${ev.commands} lệnh.</p>${personalized(ev)}<div class="actions"><button class="primary" onclick="review()">Xem đáp án chi tiết</button><button class="secondary" onclick="location.hash='practice'">Về danh sách bài</button></div></div>`}
window.review=function(){let ev=evaluate();app.innerHTML=`<div class="pagehead"><h1>Xem lại đáp án</h1><p>${esc(session.lesson.short)} • ${esc(session.lesson.title)}</p></div>`+ev.details.map((d,i)=>{let body="";if(d.q.type==="mcq")body=`<p><b>Em chọn:</b> ${Number.isInteger(d.a)?`${"ABCD"[d.a]}. ${esc(d.q.a[d.a])}`:"Chưa trả lời"}</p><p><b>Đáp án đúng:</b> ${"ABCD"[d.q.correct]}. ${esc(d.q.a[d.q.correct])}</p>`;if(d.q.type==="tf")body=d.q.statements.map((s,j)=>`<p><b>${String.fromCharCode(97+j)})</b> ${esc(s.text)} — Em: <b>${d.a?.[j]===true?"Đúng":d.a?.[j]===false?"Sai":"-"}</b> • Đáp án: <b>${s.correct?"Đúng":"Sai"}</b></p>`).join("");if(d.q.type==="short")body=`<p><b>Em trả lời:</b> ${esc(d.a||"Chưa trả lời")}</p><p><b>Đáp án đúng:</b> ${esc(d.q.answer)}</p>${d.q.solution?.length?`<div class="solution"><b>Cách tính / lời giải trong tài liệu:</b>${d.q.solution.map(x=>`<div>${esc(x)}</div>`).join("")}</div>`:""}`;return `<article class="review-card"><h3>Câu ${i+1} <span class="${d.ok?"correct":"wrong"}">${d.ok?"✓":"✗"}</span></h3><p>${esc(d.q.q||d.q.intro||"Đúng/Sai")}</p>${imgHtml(d.q)}${body}</article>`}).join("")}
function mine(){let mine=localResults.filter(r=>r.studentName===student.name&&r.className===student.className);app.innerHTML=`${identity()}<div class="pagehead"><h1>Kết quả của em</h1></div>${mine.length?`<table><thead><tr><th>Thời gian</th><th>Bài</th><th>Điểm</th></tr></thead><tbody>${mine.slice().reverse().map(r=>`<tr><td>${new Date(r.timestamp).toLocaleString("vi-VN")}</td><td>${esc(r.lessonTitle)}</td><td>${r.score}</td></tr>`).join("")}</tbody></table>`:"<div class='card'>Chưa có kết quả.</div>"}`;bindIdentity()}
function teacher(){app.innerHTML=`<div class="pagehead"><h1>Thống kê giáo viên</h1><p>Nhập khóa giáo viên để đọc dữ liệu từ Google Sheets.</p></div><div class="card"><input id="tkey" placeholder="Khóa giáo viên" style="width:100%;padding:12px;border:1px solid var(--line);border-radius:12px"><br><br><button class="primary" id="loadStats">Xem thống kê</button><div id="stats"></div></div>`;$("#loadStats").onclick=async()=>{let key=$("#tkey").value.trim();if(!key)return;$("#stats").innerHTML="<p>Đang tải…</p>";try{let r=await fetch(`${RESULT_API_URL}?action=list&key=${encodeURIComponent(key)}`),j=await r.json();if(!j.ok)throw Error(j.error||"Không đọc được dữ liệu");let rows=j.rows||[],students=new Set(rows.map(x=>`${x.studentName}|${x.className}`)),avg=rows.length?rows.reduce((s,x)=>s+Number(x.score||0),0)/rows.length:0;$("#stats").innerHTML=`<div class="personal"><b>${students.size}</b> học sinh • <b>${rows.length}</b> lượt làm • Điểm TB <b>${avg.toFixed(2)}</b></div><table><tr><th>Học sinh</th><th>Lớp</th><th>Bài</th><th>Điểm</th></tr>${rows.slice().reverse().map(x=>`<tr><td>${esc(x.studentName)}</td><td>${esc(x.className)}</td><td>${esc(x.lessonTitle)}</td><td>${x.score}</td></tr>`).join("")}</table>`}catch(e){$("#stats").innerHTML=`<p class="wrong">${esc(e.message)}</p>`}}}
function startMusic(){if(!musicOn)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();let notes=[261.63,329.63,392,329.63,293.66,349.23,440,349.23],i=0;stopMusic();musicTimer=setInterval(()=>{if(!audioCtx||!musicOn)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type="sine";o.frequency.value=notes[i++%notes.length];g.gain.setValueAtTime(.018,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.45);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.5)},650)}catch(e){}}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}function ensureMusicButton(){let b=document.querySelector(".musicctl");if(!b){b=document.createElement("button");b.className="musicctl";document.body.appendChild(b)}b.textContent=musicOn?"🔊":"🔇";b.title="Bật/tắt nhạc";b.onclick=()=>{musicOn=!musicOn;b.textContent=musicOn?"🔊":"🔇";if(!musicOn)stopMusic();else if(session)startMusic()}}
function render(){ensureMusicButton();let h=location.hash.slice(1)||"home";if(h==="home")home();else if(h==="theory")listing("theory");else if(h==="practice")listing("practice");else if(h==="mine")mine();else if(h==="teacher")teacher();else if(h.startsWith("lesson/")){let[,id,mode]=h.split("/");openLessonView(id,mode)}else home()}render();
